### ISSUE TITLE
Clarify status of API

### ISSUE THREAD

**Issue by EyalLavi** [ebu/benchmarkstt#110]
@JPEvain used the API and Explorer in the demo for IBC and found both very useful. So far, we considered them as helpers so they were out of scope (see "Important" note here: https://benchmarkstt.readthedocs.io/en/latest/api.html.

Should we one or both into the core library? What would be involved?

**Comment by amessina71** [comment]
I would like to second the option to include both components in a future release, and so to have them as full-fledged parts of the tool. In fact I used the base CLI tool for the tender I did last June and found quite useful for that.  Nevertheless, having an API exposure would tremendously enhance usability and integration.

**Comment by JPEvain** [comment]
The API is definitely key to some integration scenarios. That should be in scope.

The explorer/UI part is quite pedagogic. That should stay at least as nice to have.

In fact, when you get there through the documentation, nothing says clearly that it doesn’t have the status it seems to have. So it builds expectations also because it delivers good results.

I definitely took it as granted when I developed my demo.

Jean-Pierre

**Comment by EyalLavi** [comment]
Decided in meeting today that the API should be part of the core release. Looking for resource to review code and determine test coverage. I will open a separate issue.
