### ISSUE TITLE
Inserts and deletions prioritised calculating worddiffs/WER

### ISSUE THREAD

**Issue by cjrosen** [ebu/benchmarkstt#113]
Hi!
And thanks for initiating this project! At Swedish Radio, this is exactly the kind of tool we're thinking about and one we're definitely interested in applying in our evaluation of ASR services. We've successfully got it up and running as an api.

One thing that struck me after some experiments was that the WER wasn't so generous. An example, considering the reference text `a b C d E f g h i j`:

hypothesis `a b X d Y f g h i j` gives 2 replacements / WER=0.2, but

hypothesis `a b E d C f g h i j` gives 2 insertions and 2 deletions / WER=0.4

I guess this is because the algorithm tries to align the `C`'s, which gives an insertion of `E d` and a deletion of `d E`, rather than a replacement of `E` and `C` respectively. Is this the expected behaviour? Shouldn't the algorithm try to find the least number of modifications needed to match the reference sentence?

I haven't had the time to look at the code in detail yet, and before I do, I just wanted to throw this question out to see if it's only me?

**Comment by EyalLavi** [comment]
Hello @cjrosen, thank you for the great feedback. 

I don't have in-depth knowledge of the algorithm (we'll be very happy to hear your findings), but I believe that both standard WER definition and Python rely on the same diff algorithm. BenchmarkSTT uses the Python implementation: https://benchmarkstt.readthedocs.io/en/latest/cli.html#available%20metrics  

By default, BenchmarkSTT uses the `strict` mode of WER algorithm, but it support the more forgiving `hunt` variant, which also return a WER of 0.2: 

```
$ benchmarkstt --wer hunt -r 'a b C d E f g h i j' -rt argument -h 'a b E d C f g h i j' -ht argument`

wer
===

0.200000
```

Does this solve the problem?

**Comment by cjrosen** [comment]
Hi @EyalLavi, thanks for the quick response!

It seems like `hunt` downscores insert/delete errors, rather than actually seeing the replacements. From what I know of the WER algorithm (and I'm absolutely not an expert either!) it should be able to identify the path of least change. Like the Levenshtein distance, as visualised in this matrix:

```
           a    b    E    d    C    f    g    h    i     j
    0.0  1.0  2.0  3.0  4.0  5.0  6.0  7.0  8.0  9.0  10.0
a   1.0  0.0  1.0  2.0  3.0  4.0  5.0  6.0  7.0  8.0   9.0
b   2.0  1.0  0.0  1.0  2.0  3.0  4.0  5.0  6.0  7.0   8.0
C   3.0  2.0  1.0  1.0  2.0  2.0  3.0  4.0  5.0  6.0   7.0
d   4.0  3.0  2.0  2.0  1.0  2.0  3.0  4.0  5.0  6.0   7.0
E   5.0  4.0  3.0  2.0  2.0  2.0  3.0  4.0  5.0  6.0   7.0
f   6.0  5.0  4.0  3.0  3.0  3.0  2.0  3.0  4.0  5.0   6.0
g   7.0  6.0  5.0  4.0  4.0  4.0  3.0  2.0  3.0  4.0   5.0
h   8.0  7.0  6.0  5.0  5.0  5.0  4.0  3.0  2.0  3.0   4.0
i   9.0  8.0  7.0  6.0  6.0  6.0  5.0  4.0  3.0  2.0   3.0
j  10.0  9.0  8.0  7.0  7.0  7.0  6.0  5.0  4.0  3.0   2.0
```

Other tools that I've evaluated also finds the minimum changes necessary to rebuild the reference sentence. Like [asr_evaluation](https://github.com/belambert/asr-evaluation):

```
$ wer -c data/ref.txt data/hyp_flipCE.txt 
SUBSTITUTIONS:
C                    -> E                               1
E                    -> C                               1
Sentence count: 1
WER:    20.000% (         2 /         10)
WRR:    80.000% (         8 /         10)
SER:   100.000% (         1 /          1)
```

and [Jiwer](https://pypi.org/project/jiwer/):

```
from jiwer import wer
res = wer('a b C d E f g h i j', 'a b E d C f g h i j')
print(res)

>>> 0.2
```

So, the `hunt` algorithm does solve the problem in this particular case, but it's still, maybe, a problem with the algorithm. I don't know how often this type of case would occur in benchmarking, but it's important for us to really understand what we're measuring if we're to implement it as our benchmark.

**Comment by murezzda** [comment]
Hi!

I've also looked into this issue and it seems there is indeed a bigger difference between the "classical" Levensthein edit distance used for WER and the Ratcliff/Obershelp algorithm used in the python difflib:

The [Ratcliff/Obershelp](https://en.wikipedia.org/wiki/Gestalt_Pattern_Matching) algorithm solves iteratively the [longest common substring](https://en.wikipedia.org/wiki/Longest_common_substring_problem) problem on the string, while Levensthein solves the [longest common subsequence](https://en.wikipedia.org/wiki/Longest_common_subsequence_problem) problem, which "_[...] differs from the longest common substring problem: unlike substrings, subsequences are not required to occupy consecutive positions within the original sequences._"

The [python documentation](https://docs.python.org/3/library/difflib.html#difflib.SequenceMatcher) also states that the difflib.SequenceMatcher "_[...] does not yield minimal edit sequences, but does tend to yield matches that “look right” to people._" This is because the Ratcliff/Obershelp algorithm tries to keep long substrings intact instead of splitting them up (See also [this Medium article](https://medium.com/@nikhiljaiswal_9475/sequencematcher-in-python-6b1e6f3915fc)). This additional constraint seems to lead to suboptimal solutions for the minium edit distance problem. I would thus guess that the Ratcliff/Obershelp algorithm will tend to result in higher WER than Levensthein. Also, Wikipedia states that the Ratcliff/Obershelp algorithm is not commutative, which means switching the hypothesis and reference could change the result. This can be checked by the example from Wikipedia:
```
G E S T A L T P R A C T I C E
G E S T A L T P A T T E R N M A T C H I N G
```
Switching them between hypothesis and reference gives different WER results. This is not the case for Levensthein, which is a proper metric.

I've tried to understand how difflib handles the provided example, but I was not yet able to find out what exactly happens.

I guess as long as results from BenchmarkSTT are compared to each other, this difference does not harm too much, and it might be even a more "human friendly" way to compare strings. The problem is that as soon as someone will compare the BenchmarkSTT results with "proper" edit distance metrics, the BenchmarkSTT will tend to have higher WER scores. Also the fact that Ratcliff/Obershelp is not a metric seems a bit problematic to me.

**Comment by cjrosen** [comment]
Hi,
Thanks @murezzda for very clarifying input. I totally agree. Swedish Radio is interested in contributing to implementing the, let's call it the Levensthein implementation of WER. What would be the preferred procedure? Do we simply fork and implement, or maybe have quick call to discuss best practice, needs and structure before? What do you say @EyalLavi ?

**Comment by EyalLavi** [comment]
Thank you both for the excellent investigation. @cjrosen, you are more than welcome to join the group. This will give us the opportunity to discuss the best way to implement this change (for example, should be add this as an option or replace the underlying diff algorithm). To join, please register as a member at https://tech.ebu.ch/groups/mim

**Comment by cjrosen** [comment]
Ok, great! Have registered now (by another user name). Can't access workspace, yet, but there might be a processing delay?

**Comment by JPEvain** [comment]
I will check tomorrow. We have to invite you to slack too.

Jean-Pierre

**Comment by JPEvain** [comment]
What is it that you cannot access? Github? What do you mean by workspace in this context?

https://github.com/ebu/benchmarkstt is public

**Comment by JPEvain** [comment]
You have been added to the AI-benchmarking mailing list

**Comment by cjrosen** [comment]
Thanks @JPEvain !

**Comment by EyalLavi** [comment]
The Levenstein library does not return diffs, so `--worddiffs` will not work with the new metric. 
The Levenstein algo will not support the named entity weighted WER. The workaround will be to identify the named entity, then to either
- bag of words without taking into account position of entities. 
- calculate WER only for the found entities using existing algo or new Levenstein. 
Add `wer-ne` as a new metric for named entities WER.

Options:
1. add `--wer levenshtein` variant. Currently the variants only relate to the existing algo. 
2. add `--levenshtein` as a new metric. This is the current branch/proposal. 
3. replace existing `--wer` with new algo and add `--wer python` for the existing algo. 

Decision today:
- Option 1
- keep the `hunt` and `strict` variants, with `strict` as default

**Comment by cjrosen** [comment]
I've made a pull request (#114) that implements option 1 above. There were some issues with the tests which @danielthepope identified and solved. This pull request also adds the test case discussed in the beginning of this thread.

**Comment by EyalLavi** [comment]
@cjrosen to test the new metric and compare the results with the original metric and report back.

**Comment by cjrosen** [comment]
The two WER metrics (strict and levenshtein) were evaluated on transcripts of 10h audio (swedish) with a small difference in result. The 'strict' metric gave a WER of 27.61% (26614 errors) while the 'levenshtien' metric gave a WER of 27.15% (26163 errors). The total number of reference tokens was 96383. The 'strict' metric resulted in a 1.72% higher WER than the 'levenshtein' metric.
Of the 430 transcripts evaluated, none gave a lower 'strict' metric than 'levenshtein' metric. 99 transcripts gave higher 'strict' than 'levenshtein', while the rest were identical.
