### ISSUE TITLE
Licence

### ISSUE THREAD

**Issue by EyalLavi** [ebu/benchmarkstt#18]
Options:
- MIT
- Apache
- GPL
- BSD

**Comment by MikeSmithEU** [comment]
I propose GPLv3 (if we want to force derivative works to also share the source code) or MIT license (if we are happy with just attribution of the original work).

In general it seems the MIT licence is already being used by EBU. And the extra restrictions by the GPL licence, while well-intended and geared towards increasing open source development add some restrictions that we may not want (forcing derivative works to share their source code). Because of this, my vote would be the MIT licence.

**Comment by MikeSmithEU** [comment]
Having looked a bit into the apache licence after our recent conf. call. I quote from https://exygy.com/which-license-should-i-use-mit-vs-apache-vs-gpl/

> The Apache license has a similar philosophy to the MIT, but uses more words. The wordiness creates greater specificity about contributors’ obligations, which might help in a dispute.  But it also can be a turnoff — “Do I need to have my lawyer look at this?” comes up more with Apache than MIT. It works well for organizations or projects that are larger and managing more contributors, but don’t care about others commercializing the work.

I other words, I now profess a strong preference for either MIT or Apache licence...

**Comment by EyalLavi** [comment]
There seems to be agreement on MIT licence. Agreed in meeting today.
